import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Retina"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017"
key = "D"
mods = "Alt"

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "none"
